ARG UBUNTU_VERSION=25.10
FROM ubuntu:${UBUNTU_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    autoconf-archive \
    automake \
    ca-certificates \
    clang \
    cmake \
    curl \
    git \
    make \
    ninja-build \
    patch \
    pkg-config \
    python3 \
    unzip \
    xz-utils \
    zlib1g-dev
